services:

  nginx:
    image: public.ecr.aws/nginx/nginx:1.27
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_files:/app/static
    depends_on:
      - web
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    image: ghcr.io/codaqui/tutor-image:latest-arm64-v8
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - static_files:/app/static
      - ./private-key.pem:/app/private-key.pem
    command: >
      sh -c "python manage.py migrate 
      && python manage.py collectstatic --noinput
      && cp -r /app/staticfiles/* /app/static/
      && python manage.py runserver 0.0.0.0:8000"
    links:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  whatsapp-api:
    container_name: whatsapp_api
    image: ghcr.io/codaqui/whatsapp-api:latest-arm64-v8
    ports:
      - "3000:3000"
    volumes:
      - whatsapp_auth_data:/usr/src/app/auth_info_baileys
    environment:
      - EVENT_LOGGER_URL=http://whatsapp-app:8000/events
    networks:
      - app-network
    restart: always

  whatsapp-app:
    container_name: whatsapp_app
    image: ghcr.io/codaqui/whatsapp-app:latest-arm64-v8
    depends_on:
      - whatsapp-api
      - ollama
    networks:
      - app-network
    restart: always
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static_files:
  whatsapp_auth_data:
  ollama: {}
