# Generated by Django 5.0.6 on 2024-06-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activities",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="activities",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
