# Generated by Django 5.0.6 on 2024-06-17 23:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="Activities",
        ),
    ]
