# Generated by Django 5.0.6 on 2024-06-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_rename_transaction_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="reason",
            field=models.CharField(
                choices=[
                    ("", "Participação de aula"),
                    ("", "Certificado"),
                    ("", "Projeto"),
                    ("", "Postagem no Blog"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
