# Generated by Django 5.0.6 on 2024-06-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_activities_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activities",
            name="reason",
        ),
    ]
