# Generated by Django 5.0.6 on 2024-06-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_remove_activities_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="reason",
            field=models.CharField(
                choices=[
                    ("", "Participação de aula"),
                    ("", "Certificado"),
                    ("", "Projeto"),
                    ("", "Postagem no Blog"),
                ],
                default="Participação de aula",
                max_length=255,
            ),
        ),
    ]
