# Generated by Django 5.0.6 on 2024-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_activities_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Participação de aula", "Participação de aula"),
                    ("Certificado", "Certificado"),
                    ("Projeto", "Projeto"),
                    ("Postagem no Blog", "Postagem no Blog"),
                ],
                max_length=255,
            ),
        ),
    ]
