# Generated by Django 5.0.6 on 2024-06-22 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_alter_activities_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 22, 10, 56, 51, 250775)
            ),
        ),
    ]
