# Generated by Django 5.0.6 on 2024-06-22 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_activities_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 22, 10, 58, 32, 214702)
            ),
        ),
    ]
