# Generated by Django 5.0.6 on 2024-06-22 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0010_alter_activities_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 22, 14, 0, 14, 518996, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
