# Generated by Django 5.0.6 on 2024-06-22 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0011_alter_activities_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
