# Generated by Django 5.0.6 on 2024-05-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="age",
            new_name="birth_year",
        ),
    ]
