# Generated by Django 5.0.6 on 2024-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
