name: "Publish a GitHub Packages Container to Tutor"
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Fazer o build da imagem
      - name: Build Docker image
        run: docker build -t tutor-image .

      # 3. Enviar a imagem para o GitHub Packages
      - name: Push to GitHub Packages
        run: |
          docker tag tutor-image ghcr.io/${{ github.repository_owner }}/tutor-image:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/tutor-image:latest
